###

GET http://127.0.0.1:8080/test
# Cookie: SESSION=ZjA0ZTQ3MTktNmQ5MC00OTcyLWE3NTItNzRiMzRlODhiNTMy;

###
GET http://127.0.0.1:8080/test1
Cookie: SESSION=NWM1NDE5YjktNGQ3OS00MDk4LTliYjYtN2IxODMxYTJkZTQw;
