spring:
    redis:
        host: test
        port: 6379
    session:
        store-type: redis
        redis:
          namespace: ospp
sample:
    session:
        redis:
            # host: 192.168.1.101
            host: 127.0.0.1
            port: 6379
    cache:
        redis:
            host: 192.168.1.101
            port: 6380